### ISSUE TITLE
I have streamlink and node 18

### ISSUE THREAD

**Issue by refriedfood** [EmeraldSysDev/nhl66-client#1]
But I can't get this to work. Any step-by-step you can provide?

Thanks.

**Comment by ryand56** [comment]
Some games won't work as of right now due to many sources the games may be streamed on, most games are through ESPN+ but you might have trouble with some games. Support for these sources are planned and will be added in the near future. I also recommend having VLC installed as the player.

[This list](https://www.espn.com/espnplus/schedule/_/type/upcoming/categoryId/2512ac76-a335-39cb-af51-b9afffc6571d/channel/ESPN_PLUS/country/us/redirected/true) will show the games that are upcoming today that are available to stream with this client. (Under NHL)

**Comment by ryand56** [comment]
As for getting it to work, make sure you start the client using this command ([pnpm](https://pnpm.io/) recommended but you can use npm instead):
```pnpm run start```

**Comment by refriedfood** [comment]
There is the problem. I was trying to get node and streamlink to work in windows, not *nix. I didn't realize you were building a client. Thanks for the answer.

**Comment by ryand56** [comment]
Oh, this works on all platforms as far as I know.

**Comment by refriedfood** [comment]
Any idea how I would run it in that case? both node and streamlink are two separate executables.

**Comment by ryand56** [comment]
Streamlink should be installed in your path. This way, Node can run the process and open the stream.

**Comment by refriedfood** [comment]
That is right, and that's where I was when I made this post :) I can't get node or streamlink to work with each other via the prompt. (they are already in paths, etc)

**Comment by ryand56** [comment]
That's strange.. It is working on my end starting the client from the command line using the command above. Do you have any errors when starting the client?

**Comment by refriedfood** [comment]
Neither npm or pnpm command works for me. What is the command you're using and where do the files NEED to reside?

**Comment by ryand56** [comment]
Node should have installed npm along with it. Double check that you don't have a portable version. I would recommend using something like a [version manager](https://github.com/nvm-sh/nvm) or using the official Node installer.

**Comment by ryand56** [comment]
Make sure you are also running the command above where the files reside.

**Comment by refriedfood** [comment]
````
> pnpm run start
pnpm run start

Uncaught SyntaxError: Unexpected identifier
```

**Comment by ryand56** [comment]
Don't run the command in Node command prompt, just regular command prompt.

**Comment by refriedfood** [comment]
```
> nhl66-client@0.0.1 start
> ts-node -T src/index.ts

'ts-node' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ryand56** [comment]
Make sure you install the dependencies:
``pnpm i``

**Comment by refriedfood** [comment]
Nah, they are there. Too many hoops, not enough info and no documentation. I give up.

**Comment by ryand56** [comment]
It is not intended for public use at the moment anyways. :) I have lots of things to do still and I'm going to do some testing tomorrow. I appreciate the effort and thanks for opening this issue.
